parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: tatooine
    database_user: root
    database_password: darkside
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: d07b1824aa8c46d877f1a05abf8638a320467f7a
    database_path: null
